alter TABLE `partner` add (
  `birNumber` varchar(32) default NULL COMMENT 'BIR 号码',
  `chargerName` varchar(32) default NULL COMMENT '公司负责人名称',
  `zipCode` varchar(32) default NULL COMMENT '公司所在地邮编',
  `storeHouseRegion` int(11) default NULL COMMENT '仓库所在地区',
  `storeHouseAddress` varchar(255) default NULL COMMENT '公司仓库详细地址',
  `landmark` varchar(255) default NULL COMMENT '仓库所在地地标',
  `pickUpDate` smallint(6) default NULL COMMENT '仓库提货时间:0:Mon-Fri 1:Mon-Sat 2:Mon-Sun',
  `pickUpTime` varchar(32) default NULL COMMENT '仓库提货时间',
  `shopName` varchar(32) default NULL COMMENT '店铺名称',
  `businessNature` smallint(6) default NULL COMMENT '业务性质 0:Global Player/ Global Brand 1:SEA/ National Brand 2:International Retail Chain (3+ countries) 3:Global Player representative 4:Official importer/ distributor of brand (principle) 5:Retail chain (10+ stores) 6:Retailer (<10 stores) 7:White label man',
  `businessYears` smallint(6) default NULL COMMENT '经营年限：0:0-1 1:1-5 2:5-10 3:10 and years above',
  `mainCategoryId` int(12) default NULL COMMENT '主要经营品类',
  `isLicenseValid` smallint(6) default NULL COMMENT '是否有合法执照',
  `isOwner` smallint(6) default NULL COMMENT '是否是商品所有这',
  `intendBrands` varchar(64) default NULL COMMENT '希望销售商品',
  `skuNumber` smallint(6) default NULL COMMENT '店铺销售SKU数量 0:30 sku below 1:30-100 2:100-200 3:200-400 4:400-1000 5:1000-10000 6:1000 and above',
  `otherPlatform` smallint(6) default NULL COMMENT '是否在其他平台销售',
  `bankName` varchar(64) default NULL COMMENT '开户银行名称',
  `accountName` varchar(32) default NULL COMMENT '开户人姓名',
  `accountNumber` varchar(32) default NULL COMMENT '银行账户账号',
  `birRegistration` varchar(64) default NULL COMMENT 'BIR 证书',
  `dtiRegistration` varchar(64) default NULL COMMENT 'DTI/SEC 证书',
  `businessPermit` varchar(64) default NULL COMMENT '执业许可',
  `collectionReceipt` varchar(64) default NULL COMMENT '缴款收据'
)